#Tomcat port átírása
#server:
#  port: 8280
#  servlet:
#    context-path: /gamebase

spring:
  thymeleaf:
    cache: false


logging:
  level:
    hu: TRACE


#szó adatbázis
game:
  words:  uszoda sajt IKEA íj ketchup tüzijáték homok